# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSysArchiveConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(default='/tmp/', help_text='Vidispine must have write access to the given storage path', max_length=255, verbose_name='Storage path')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
